### PR TITLE
Mm/attempt to deploy with graphql

### PR DESCRIPTION
**Pull request by MarchandMD**
Why is this PR made? 

Attempting to deploy to Heroku resulted in an error; this PR is attempting to resolve this error

How is this PR helping? 

the .gitignore file has been udpated and GraphQL has been implemented; this is an attempt to deploy prior to pre-compiling assets locally; A second PR may be required

### CODE REVIEW

**Comment by MarchandMD** [comment]
I'm attempting to deploy. this may include a couple of quick PRs with some new fixes; fyi

**Comment by MarchandMD** [comment]
Hold please...

**Comment by MarchandMD** [comment]
Merge conflicts resolved

**Review by ajpulzone — APPROVED** [review]
Reviewed code, Circle CI passing. Pulled branch locally and nothing broke.

Will merge to main.

**Pull request merged**
